language: r

r:
  - oldrel
  - release
  - devel

cache: packages

warnings_are_errors: false

jobs:
  include:
    - stage: deploy
      language: r
      r: release
      r_github_packages:
        - r-lib/covr
        - r-lib/pkgdown
      script:
        - make docs
        - Rscript -e 'covr::codecov()'
      deploy:
        # Deploy documentation to Github Pages
        # See https://docs.travis-ci.com/user/deployment/pages/
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: docs
    - stage: release
      language: node_js
      node_js: '12.0'
      script: skip
      deploy:
        # Do a semantic release if necessary. See `.releaserc` for config.
        - provider: script
          skip_cleanup: true
          script: npx semantic-release
