language: r

r:
  - oldrel
  - release
  - devel

cache: packages

warnings_are_errors: false

# Deploy documentation, and upload code coverage
# using the current release version of R
jobs:
  include:
    - stage: deploy
      r: release
      r_github_packages:
        - r-lib/covr
        - r-lib/pkgdown
      script:
        - make docs
        - Rscript -e 'covr::codecov()'
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: docs
        on:
          branch: master
