jobs:
  - job: test
    strategy:
      matrix:
        linux_40:
          r_version: '4.0.3'
        linux_36:
          r_version: '3.6.3'
    pool:
      vmImage: ubuntu-latest
    container:
      image: 'rocker/r-ver:$(r_version)'
    variables:
      R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
    steps:
      - script: |
          sudo apt-get update && sudo apt-get install -y libxml2-dev libssl-dev
          mkdir -p $(R_LIBS_USER)
          Rscript -e "install.packages('remotes', lib = '$(R_LIBS_USER)', repos = 'https://cloud.r-project.org')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, lib = '$(R_LIBS_USER)')"
        displayName: 'Install dependencies'

      - script: make lint
        displayName: 'Run linting'
      
      - script: make test
        displayName: 'Run tests'

      - script: make check
        displayName: 'Check package'
