jobs:
  - job: test
    strategy:
      matrix:
        linux_40:
          r_version: '4.0.3'
        linux_36:
          r_version: '3.6.3'
    pool:
      vmImage: ubuntu-latest
    container:
      image: 'rocker/r-ver:$(r_version)'
    variables:
      R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
    steps:
      - script: |
          echo 'options(repos = "https://cloud.r-project.org", Ncpus = 2, crayon.enabled = TRUE)' > ~/.Rprofile
          mkdir -p $(R_LIBS_USER)
        displayName: "Setup R library"
        
      - script: make setup
        displayName: 'Install dependencies'

      - script: make lint
        displayName: 'Run linting'
      
      - script: make test
        displayName: 'Run tests'

      - script: make check
        displayName: 'Check package'
